// Code generated by goctl. DO NOT EDIT.
package types

type FileDownLoadRequest struct {
	Identity string `json:"identity"`
}

type FileDownLoadResponse struct {
	Msg string `json:"msg"`
}

type ShareFilePullRequest struct {
	Identity string `json:"identity"`
}

type ShareFilePullResponse struct {
	Msg string `json:"msg"`
}

type ShareFileDownloadRequest struct {
	Identity string `json:"identity"`
}

type ShareFileDownloadResponse struct {
	Msg string `json:"msg"`
}

type ShareFileListRequest struct {
	PageNum  int `json:"page,optional"`
	PageSize int `json:"size,optional"`
}

type ShareFileListResponse struct {
	Count int64        `json:"count"`
	List  []*ShareFile `json:"list"`
}

type ShareFile struct {
	Identity    string `json:"identity"`
	Name        string `json:"name"`
	Ext         string `json:"ext"`
	Path        string `json:"path"`
	Size        int64  `json:"size"`
	ExpiredTime int    `json:"expired_time"`
	ClickNum    int    `json:"click_num"`
}

type ShareFileRequest struct {
	ExpiredTime int    `json:"expired_time"`
	Identity    string `json:"identity"`
}

type ShareFileResponse struct {
	Msg      string `json:"msg"`
	Identity string `json:"identity"`
}

type UserFileOwenUpdateRequest struct {
	Identity     string `json:"identity"`
	UserIdentity string `json:"user_identity"`
}

type UserFileOwenUpdateResponse struct {
	Msg string `json:"msg"`
}

type UserFileDeleteRequest struct {
	Identity string `json:"identity"`
}

type UserFileDeleteResponse struct {
	Msg string `json:"msg"`
}

type UserFileNameUpdateRequest struct {
	Identity string `json:"identity"`
	NewName  string `json:"new_name"`
}

type UserFileNameUpdateResponse struct {
	Msg string `json:"msg"`
}

type UserFileListRequest struct {
	PageNum  int `json:"page,optional"`
	PageSize int `json:"size,optional"`
}

type UserFileListResponse struct {
	Count int64       `json:"count"`
	List  []*UserFile `json:"list"`
}

type UserFile struct {
	Id                 int64  `json:"id"`
	Identity           string `json:"identity"`
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Path               string `json:"path"`
	Size               int64  `json:"size"`
}

type UserRepositorySaveRequest struct {
	ParentId           int64  `json:"parentId"`
	RepositoryIdentity string `json:"repository_identity"`
	Ext                string `json:"ext"`
	Name               string `json:"name"`
}

type UserRepositorySaveResponse struct {
}

type FileUploadRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type FileUploadResponse struct {
	Identity string `json:"identity"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type DetailRequest struct {
	Identity string `json:"identity"`
}

type DetailResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type MailSendRequest struct {
	Email string `json:"email"`
}

type MailSendResponse struct {
	Msg string `json:"msg"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type UserRegisterResponse struct {
	Msg string `json:"msg"`
}
